service: user
# app and org for use with dashboard.serverless.com

frameworkVersion: "3"

useDotenv: true
provider:
  name: aws
  timeout: 10
  runtime: nodejs16.x
  region: sa-east-1

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  getUserByEmail:
    handler: ./router/userWebRouter.getUserByEmail
    events:
      - httpApi:
          path: /api/user/{email}
          method: get

  getAllUsers:
    handler: ./router/userWebRouter.getAllUsers
    events:
      - httpApi:
          path: /api/users
          method: get

  postNewUser:
    handler: ./router/userWebRouter.postNewUser
    events:
      - httpApi:
          path: /api/user
          method: post

  putUser:
    handler: ./router/userWebRouter.putUser
    events:
      - httpApi:
          path: /api/user/{id}
          method: put

  deleteUser:
    handler: ./router/userWebRouter.deleteUser
    events:
      - httpApi:
          path: /api/user/{id}
          method: delete

  # listUser:
  #   handler: userRouter.getUser
  #   events:
  #     - httpApi:
  #         path: /user
  #         method: get

  # createUser:
  #   handler: userRouter.addUser
  #   events:
  #     - httpApi:
  #         path: /new-user
  #         method: post

  # updateUser:
  #   handler: userRouter.updateUser
  #   events:
  #     - httpApi:
  #         path: /user/{id}
  #         method: put

  # deleteUser:
  #   handler: userRouter.deleteUser
  #   events:
  #     - httpApi:
  #         path: /user/{id}
  #         method: delete
